# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
