# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20170928_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecommerce.Admin')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_purchased',
        ),
    ]
