# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_item_quantity_purchased'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Adminuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
